{
    "swagger": "2.0",
    "info": {
        "description": "SmartComex integrations API",
        "title": "SmartComex API",
        "termsOfService": "https://smartcomex.io/pt-br/termos-de-uso/",
        "contact": {
            "name": "Support",
            "email": "support@smartcomex.io"
        },
        "version": "0.0.1"
    },
    "host": "api.smartcomex.io",
    "basePath": "/v1",
    "paths": {
        "/contacts": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "contact:read"
                        ]
                    }
                ],
                "description": "Get a list of contacts",
                "tags": [
                    "Contact"
                ],
                "summary": "Contact list"
            }
        },
        "/fromtos": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "fromto:read"
                        ]
                    }
                ],
                "description": "Get a list of FromTo conversions",
                "tags": [
                    "FromTo"
                ],
                "summary": "FromTo list"
            }
        },
        "/offices": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "office:read"
                        ]
                    }
                ],
                "description": "Get a list of offices",
                "tags": [
                    "Office"
                ],
                "summary": "Offices list"
            }
        },
        "/offices/internal": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "office:read"
                        ]
                    }
                ],
                "description": "Get a list of organization offices",
                "tags": [
                    "Office"
                ],
                "summary": "Organization's offices list"
            }
        },
        "/offices/{office_code}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "office:read"
                        ]
                    }
                ],
                "description": "Get a office by office code",
                "tags": [
                    "Office"
                ],
                "summary": "Retrieve a office"
            }
        },
        "/process_request": {
            "put": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process_request:write"
                        ]
                    }
                ],
                "tags": [
                    "Process Request"
                ],
                "summary": "Add a process update request"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process_request:write"
                        ]
                    }
                ],
                "tags": [
                    "Process Request"
                ],
                "summary": "Add a process creation request"
            }
        },
        "/process_requests/{idRequest}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process_request:read"
                        ]
                    }
                ],
                "description": "Get a process request information by idRequest",
                "tags": [
                    "Process Request"
                ],
                "summary": "Retrieve a process creation/update request"
            }
        },
        "/processes": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a process by process code",
                "tags": [
                    "Process"
                ],
                "summary": "Processes list"
            }
        },
        "/processes/{process_code}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a process by process code",
                "tags": [
                    "Process"
                ],
                "summary": "Retrieve a process"
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Application": {
            "type": "oauth2",
            "flow": "application",
            "tokenUrl": "https://auth.smartcomex.io/oauth2/token"
        }
    }
}