{
    "swagger": "2.0",
    "info": {
        "description": "SmartComex integrations API",
        "title": "SmartComex API",
        "termsOfService": "https://smartcomex.io/pt-br/termos-de-uso/",
        "contact": {
            "name": "Support",
            "email": "support@smartcomex.io"
        },
        "version": "0.0.1"
    },
    "host": "connect.smartcomex.io",
    "basePath": "/v1",
    "paths": {
        "/async_requests/{idRequest}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "async_request:read"
                        ]
                    }
                ],
                "description": "Get a async request information by idRequest",
                "tags": [
                    "Async Requests"
                ],
                "summary": "Retrieve creation/update async request information"
            }
        },
        "/contacts": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "contact:read"
                        ]
                    }
                ],
                "description": "Get a list of contacts",
                "tags": [
                    "Contacts"
                ],
                "summary": "Contacts list"
            }
        },
        "/mappings": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "read"
                        ]
                    }
                ],
                "description": "Get a list of mappings",
                "tags": [
                    "Mappings"
                ],
                "summary": "Mappings list"
            }
        },
        "/offices": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "office:read"
                        ]
                    }
                ],
                "description": "Get a list of offices",
                "tags": [
                    "Offices"
                ],
                "summary": "Offices list"
            }
        },
        "/offices/{office_code}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "office:read"
                        ]
                    }
                ],
                "description": "Get a office by office code",
                "tags": [
                    "Offices"
                ],
                "summary": "Retrieve a office"
            }
        },
        "/process/{process_code}/charges": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a list of process charges",
                "tags": [
                    "Process Charges"
                ],
                "summary": "Process charges list"
            },
            "put": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:write"
                        ]
                    }
                ],
                "description": "Update process charges in a process",
                "tags": [
                    "Process Charges"
                ],
                "summary": "[Async] Update process charges"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:write"
                        ]
                    }
                ],
                "description": "Add process charges in a process",
                "tags": [
                    "Process Charges"
                ],
                "summary": "[Async] Add process charges"
            }
        },
        "/process/{process_code}/charges/{process_charge_id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a process charge by id",
                "tags": [
                    "Process Charges"
                ],
                "summary": "Process charge by id"
            }
        },
        "/process/{process_code}/volumes": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a list of process volumes",
                "tags": [
                    "Process Volumes"
                ],
                "summary": "Process volumes list"
            },
            "put": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:write"
                        ]
                    }
                ],
                "description": "Update process volumes in a process",
                "tags": [
                    "Process Volumes"
                ],
                "summary": "[Async] Update process volumes"
            },
            "post": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:write"
                        ]
                    }
                ],
                "description": "Add process volumes in a process",
                "tags": [
                    "Process Volumes"
                ],
                "summary": "[Async] Add process volumes"
            }
        },
        "/process/{process_code}/volumes/{process_volume_id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a process volume by id",
                "tags": [
                    "Process Volumes"
                ],
                "summary": "Process volume by id"
            }
        },
        "/processes": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a process by process code",
                "tags": [
                    "Processes"
                ],
                "summary": "Processes list"
            }
        },
        "/processes/other_services": {
            "post": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:write"
                        ]
                    }
                ],
                "tags": [
                    "Processes"
                ],
                "summary": "[Async] Request process creation [other Services]"
            }
        },
        "/processes/other_services/{process_code}": {
            "put": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:write"
                        ]
                    }
                ],
                "tags": [
                    "Processes"
                ],
                "summary": "[Async] Request process update [other Services]"
            }
        },
        "/processes/{process_code}": {
            "get": {
                "security": [
                    {
                        "OAuth2Application": [
                            "process:read"
                        ]
                    }
                ],
                "description": "Get a process by process code",
                "tags": [
                    "Processes"
                ],
                "summary": "Retrieve a process"
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Application": {
            "type": "oauth2",
            "flow": "application",
            "tokenUrl": "https://auth.smartcomex.io/oauth2/token"
        }
    }
}